lib/newstore_web/router.ex
defmodule NewstoreWeb.Router do
  use NewstoreWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NewstoreWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/shoppingcart", ShoppingcartController, :index
    get "/products", ProductsController, :index
    get "/storage", StorageController, :index
    get "/admin", AdminController, :index
    get "/reguser", ReguserController, :index
    get "/about", AboutController, :index
    get "/tos", TosController, :index
    get "/my_profile", UserController, :my_profile

    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
    resources "/user", UserController
  end

  scope "/admin", NewstoreWeb do
    get "/adminuser", AdminuserController, :index
    get "/adminproduct", AdminproductController, :index
  end
  # Other scopes may use custom stacks.
  # scope "/api", NewstoreWeb do
  #   pipe_through :api
  # end
end

lib/newstore/application.ex
defmodule Newstore.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Newstore.Repo, []),
      # Start the endpoint when the application starts
      supervisor(NewstoreWeb.Endpoint, []),
      # Start your own worker by calling: Newstore.Worker.start_link(arg1, arg2, arg3)
      # worker(Newstore.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Newstore.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    NewstoreWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/newstore/repo.ex
defmodule Newstore.Repo do
  use Ecto.Repo, otp_app: :newstore

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/newstore_web/controllers/page_controller.ex
defmodule NewstoreWeb.PageController do
  use NewstoreWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/newstore_web/controllers/tos_controller.ex
defmodule NewstoreWeb.TosController do
    use NewstoreWeb, :controller

    def index(conn, _params) do
      render conn, "index.html"
    end
end

lib/newstore_web/controllers/user_controller.ex
defmodule NewstoreWeb.UserController do
    use NewstoreWeb, :controller
    alias Prios.Repo
    alias Prios.Identity
    alias Prios.Identity.User
    alias Prios.Identity.Login
    alias Prios.Helpers.Auth

    plug :check_auth when action in [:my_profile]

defp check_auth(conn, _args) do
  if login_id = get_session(conn, :current_login_id) do
  current_user = Identity.get_login(login_id)
  conn
    |> assign(:current_user, current_user)
  else
    conn
    |> put_flash(:error, "You need to be signed in to access this page.")
    |> redirect(to: page_path(conn, :index))
    |> halt()
  end
end

def index(conn, _params) do
  users = Identity.list_users()
  render(conn, "index.html", users: users)
end

def new(conn, _params) do
  changeset = Identity.change_login(%Login{users: %User{}})
  render(conn, "new.html", changeset: changeset)
end

def create(conn, %{"login" => login_params}) do
  case Identity.create_login(login_params) do
    {:ok, login} ->
      conn
      |> put_session(:current_login_id, login.id)
      |> put_flash(:info, "Signed up successfully.")
      |> redirect(to: page_path(conn, :index))
    {:error, %Ecto.Changeset{} = changeset} ->
      render(conn, "new.html", changeset: changeset)
  end
end

def my_profile(conn, _params) do
  login = Auth.my_user(conn)
  render(conn, "show.html", login: login)
end

def show(conn, %{"id" => id}) do
  user = Identity.get_user(id)
  login = Identity.get_login(id)
  render(conn, "show.html", user: user, login: login)
end
  
    
end
  

lib/newstore_web/views/about_view.ex
defmodule NewstoreWeb.AboutView do
    use NewstoreWeb, :view
end

lib/newstore_web/views/admin_view.ex
defmodule NewstoreWeb.AdminView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/adminproduct_view.ex
defmodule NewstoreWeb.AdminproductView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/adminuser_view.ex
defmodule NewstoreWeb.AdminuserView do
  use NewstoreWeb, :view
end
  

lib/newstore_web/views/error_view.ex
defmodule NewstoreWeb.ErrorView do
  use NewstoreWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/newstore_web/views/info_view.ex
defmodule NewstoreWeb.Shared.Product.InfoView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/layout_view.ex
defmodule NewstoreWeb.LayoutView do
  use NewstoreWeb, :view
end

lib/newstore_web/views/page_view.ex
defmodule NewstoreWeb.PageView do
  use NewstoreWeb, :view
end

lib/newstore_web/views/product_view.ex
defmodule NewstoreWeb.ProductView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/products_view.ex
defmodule NewstoreWeb.ProductsView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/reguser_view.ex
defmodule NewstoreWeb.ReguserView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/session_view.ex
defmodule NewstoreWeb.SessionView do
    use NewstoreWeb, :view
end

lib/newstore_web/views/shoppingcart_view.ex
defmodule NewstoreWeb.ShoppingcartView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/storage_view.ex
defmodule NewstoreWeb.StorageView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/views/tos_view.ex
defmodule NewstoreWeb.TosView do
    use NewstoreWeb, :view
end

lib/newstore_web/views/user_view.ex
defmodule NewstoreWeb.UserView do
    use NewstoreWeb, :view
end
    

lib/newstore_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Hello Newstore!</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>
<body class="sq-viewport">
  <!-- Grid start -->
  <div class="sq-page">
    <!--NavBar start-->
    <nav class="sq-nav-area" style="min-height:6rem;">
      <div class="sq-navbar-layout">
        <!--NavBar part 1/3-->
        <div class="sq-navbar-nav sq-secondary sq-text-right sq-force-2">
          <!-- Links -->
          <div class=" sq-flex sq-air-x-05 sq-justify-evenly">
            <a href="#" class="sq-text-white sq-secondary  sq-x-padding-05"></a>
            <a href="#" class="sq-text-white sq-secondary  sq-x-padding-05"></a>
            <a href="#" class="sq-text-white sq-secondary"></a>
          </div>
        </div>
        <!--NavBar part 2/3-->
        <div class="sq-navbar-domain sq-secondary sq-flex sq-force-2 sq-justify-around">

          <div class="sq-flex sq-force-left" style="margin-left: 1em; font-weight: bold;"><a href="/" class="sq-text-white sq-secondary"><img src="/images/newStore.png" alt="" style="height: 200%; width 200%; margin-top: -2em;"> </a></div>
          <!-- SearchBar -->
          <div class=" sq-flex sq-justify-center sq-width-300em sq-form  sq-height-80p">
           <input type="text" placeholder="Search" name="search" class="sq-air-r-05" style="border-radius: 5px 0px 0px 5px; background-color: #dff0d8;">
            <button class="sq-button1" style="height: 100%; border-radius: 0px 5px 5px 0px;" type="submit">Search</button>
          </div>
          <!--SearchBar end-->
          <!--SignIn button -->
          <div class="sq-flex sq-flex-row sq-force-right" style="margin-right: 1em;">
            <div class="sq-text-center">
              <button class="sq-button1 sq-height-80p" onclick="toggleModal('myModal')" style=" margin-right: 1em; margin-top: 0; background-color: var(--secondary-highlight)">Login / Register</button>
              <!-- modal start -->
              <div class="sq-modal" id="myModal">
                <div class="sq-modal-content" style="width: 20em; height: 12em;">
                  <header>
                    <span class="sq-close" onclick="toggleModal('myModal')">&times;</span>
                  </header>
                  <section>
                    <form class="sq-form sq-text-base" action="index.html" method="post">
                      <fieldset>
                        <legend>Login</legend>
                        <label>Email</label>
                        <input type="email" name="" value="" placeholder="E-mail">
                        <label>Password</label>
                        <input type="password" name="" value="" placeholder="Password">
                        <div class="sq-flex-container-middle">
                          <div class="sq-force-left">
                            <a href="/admin">
                              <button type="button" name="">Login</button>
                            </a>
                          </div>
                          <a href="/reguser">
                            <div class="sq-force-right">
                              <button type="button" name=""><%= link "Sign up", to: user_path(@conn, :new) %></button>
                            </div>
                          </a>
                        </div>
                      </fieldset>
                    </form>
                  </section>
                </div>
              </div>
              <script>
              function toggleModal(id) {
                var modal = document.getElementById(id);
                modal.classList.toggle("sq-show-modal");
              }
              </script>

            </div>
            <!--Modal end -->
            <!--SignIn button end -->
            <!--ShoppingCart button -->
            <button class="sq-nav-dropdown sq-button1 sq-height-80p sq-width-30em">
              <svg id="i-cart" viewBox="0 0 32 32" width="20" height="20" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                <path d="M6 6 L30 6 27 19 9 19 M27 23 L10 23 5 2 2 2" />
                <circle cx="25" cy="27" r="2" />
                <circle cx="12" cy="27" r="2" />
              </svg>
              <div class=" sq-secondary sq-nav-dropdown-content-right">
                <div class="sq-card">
                  <div class="sq-flex sq-justify-evenly">
                    <img class="sq-border-1 sq-air-t-10" style="min-width:5em; max-width:5em; max-height:5em; min-height:5em;"></img>
                    <div>
                      <p>Pris:</p>
                      <p>500-,</p>
                    </div>
                  </div>
                  <div class="sq-flex sq-justify-evenly">
                    <img class="sq-border-1 sq-air-t-10" style="min-width:5em; max-width:5em; max-height:5em; min-height:5em;"></img>
                    <div>
                      <p>Pris:</p>
                      <p>500-,</p>
                    </div>
                  </div>
                  <div class="sq-flex sq-justify-evenly">
                    <img class="sq-border-1 sq-air-t-10" style="min-width:5em; max-width:5em; max-height:5em; min-height:5em;"></img>
                    <div>
                      <p>Pris:</p>
                      <p>500-,</p>
                    </div>
                  </div>
                  <div class="sq-flex sq-justify-evenly">
                    <img class="sq-border-1 sq-air-t-10" style="min-width:5em; max-width:5em; max-height:5em; min-height:5em;"></img>
                    <div>
                      <p>Pris:</p>
                      <p>500-,</p>
                    </div>
                  </div>
                  <div class="sq-flex sq-justify-evenly">
                    <img class="sq-border-1 sq-air-t-10" style="min-width:5em; max-width:5em; max-height:5em; min-height:5em;"></img>
                    <div>
                      <br>
                      <p>Pris:</p>
                      <p>500-,</p>
                    </div>
                  </div>
                  <div class="sq-force-right">
                    <p>Sum: 2500-,</p>
                  </div>
                  <a class="sq-secondary-highlight sq-button1" href="/shoppingcart">To shoppingcart</a>
                </div>
              </div>
            </button>
          <!--ShoppingCart button end -->
          </div>
        </div>
        <!-- Navbar part 3/3-->
        <div class="sq-navbar-links sq-secondary-highlight sq-text-center sq-force-2 sq-border-nav">
          <div class="sq-nav-btn-group sq-flex sq-justify-evenly" style="margin-top: 0.1em;">
          <ul class="nav nav-pills pull-right">
            <%= if signed_in?(@conn) do %>
            <li><%= link "Sign out", to: session_path(@conn, :delete), method: :delete %></li>
            <li><%= link my_user(@conn).username, to: user_path(@conn, :my_profile) %></li>
          
            <% else %>
              <li><%= link "Sign In", to: session_path(@conn, :new) %></li>
              <li><%= link "Sign up", to: user_path(@conn, :new) %></li>
            <% end %>
          </ul>
           <button><a href="#">Categories</a></button>
           <button><a href="/products">Products</a></button>
            <button><a href="/products">Top sellers</a></button>
           <button><a href="/products">Campaign</a></button>
          </div>
        </div>
      </div>
    </nav>
      <!--NavBar end-->
      <!-- Main content start -->
    <main class="sq-main">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer class="sq-footer sq-secondary-highlight">
      <div style="justify-content: space-around;" class="sq-secondary-highlight sq-flex sq-flex-row sq-justify-center">
        <div>
          Phone: <a href="tel:0000" class="sq-secondary-highlight sq-text-white">#########</a>
        </div>
        <div>
          <a href="mailto:nobody@online.no" class="sq-secondary-highlight sq-text-white">Mail</a>
        </div>
        <div>
          <a href="/about" class="sq-secondary-highlight sq-text-white">About</a>
        </div>
        <div>
          <a href="/tos" class="sq-secondary-highlight sq-text-white">Terms of service</a>
        </div>
      </div>
    </footer>
  </div>
    <!-- Grid end-->
    <script src="<%= static_path(@conn, "/js/app.js") %>">
    </script>
</body>
</html>